### ISSUE TITLE
CpG loci annotation in beta file

### ISSUE THREAD

**Issue by chloezhu** [nloyfer/wgbs_tools#10]
Hi,

Your work is fantastic! Thanks for your documentation and tutorial.

I understand that in the beta file, the CpGs are indexed in the order of genomic loci, and that I can convert the CpG index into genomic loci with wbgstools. But when I load the beta file into R, I don't have such loci information for each CpG. I am wondering if it's possible to  have an annotation file which matches the CpG indexes to genomic loci and gene (h19 and hg38). That would be really helpful if others want to process the beta file with R or other language. 

kind regards,
Tianyu

**Comment by nloyfer** [comment]
Hi Tianyu,
Thank you.
This annotation file probably already exists on your local machine. Let's take hg38 for example. When you run `wgbstools init_genome hg38`, it creates the directory `references/hg38/` and constructs an index file called  `references/hg38/CpG.bed.gz`.
The number of rows matches the number of rows in the beta files. 
The first column is the chromosome, the second is loci and the third is CpG-index.
```
# init_genome command constructs this "dictionary" file
$ wgbstools init_genome hg38
...
$ gunzip -c references/hg38/CpG.bed.gz | head -3
chr1    10469   1
chr1    10471   2
chr1    10484   3
$ gunzip -c references/hg38/CpG.bed.gz | wc -l
29401795
```

**Comment by chloezhu** [comment]
> Hi Tianyu, Thank you. This annotation file probably already exists on your local machine. Let's take hg38 for example. When you run `wgbstools init_genome hg38`, it creates the directory `references/hg38/` and constructs an index file called `references/hg38/CpG.bed.gz`. The number of rows matches the number of rows in the beta files. The first column is the chromosome, the second is loci and the third is CpG-index.
> 
> ```
> # init_genome command constructs this "dictionary" file
> $ wgbstools init_genome hg38
> ...
> $ gunzip -c references/hg38/CpG.bed.gz | head -3
> chr1    10469   1
> chr1    10471   2
> chr1    10484   3
> $ gunzip -c references/hg38/CpG.bed.gz | wc -l
> 29401795
> ```

Thanks! This is really helpful!
