### ISSUE TITLE
Clarify dependencies

### ISSUE THREAD

**Issue by abcoxyzide** [nloyfer/wgbs_tools#11]
Hi, thanks for making this tool!

I installed `wgbs_tools` on our machine and tried to run the `init_genome` command. During setup & running, I found a few dependencies that need to be in the environment that's not mentioned in the markdown. Thought it might be useful for you & others to know.

They are:
- numpy module (python3)
- pandas module (python3)
- tabix / bgzip

**Comment by nloyfer** [comment]
Done. Thank you!
