### ISSUE TITLE
Missing chromosomes after bam2pat

### ISSUE THREAD

**Issue by GMFranceschini** [nloyfer/wgbs_tools#12]
Hi, thanks for developing wgbstools,
I am following your workflow and encounter this problem: when creating pat and beta files from my bam files (generated with bismark), I miss entire chromosomes (everything is NA after collapsing the beta to blocks with wgbstools). 

This happens in all my samples. Do you have any idea of what might be the culprit here?
Maybe something related to how the bam is sorted?

The missing chrs are 22, 20, 16, 12, 11, 10, 8, 7, 6, 4, 3, 2 ... I see no pattern. 
The genome version matches the bam, so that shouldn't be the problem. 

Sorry If I can't provide a reproducible example, I will try to investigate the issue better in the meantime.

**Comment by yonniejon** [comment]
Hi,

I am not the main author but will try to help. 

What genome file did you set as the default the genome during wgbstools init_genome command?
Does the genome file have all chromosomes?

Do the bam files have all chromosomes? Can you see reads using samtools view of all chromsomes? If not then I would suggest posting the wgbstools log output from running the bam2pat command

**Comment by GMFranceschini** [comment]
Thank you.
The genome version used for `init_genome` is the same of those bam files, hg19. In the `reference` folder, I can see the genome has all chromosomes.
I can see all chromosomes in my bam files using `samtools idxstats`.  Indeed I have DNAme counts for all chromosomes, so the reads are there.
I will run the command again and get back to you with the log.

**Comment by GMFranceschini** [comment]
Hi, the log looks like this (not complete).
Let me know if you have more ideas about investigating the matter.

```
[ patter ] [ chr21 ] finished 10,692,072 lines. (5,346,036 pairs). 6,182,764 good, 4,509,308 empty, 0 invalid. 696,533 bad conversion. (success 100%)
[ patter ] [ chr18 ] line 15,000,000 in 2.3 minutes.
[ patter ] [ chrX ] line 10,000,000 in 2.3 minutes.
[ patter ] [ chr20 ] line 5,000,000 in 2.4 minutes.
[ patter ] [ chr22 ] line 5,000,000 in 2.4 minutes.
[match maker] [ chr18 ] finished 19,059,350 lines.
[ patter ] [ chr18 ] finished 19,059,350 lines. (9,529,675 pairs). 10,505,924 good, 8,553,426 empty, 0 invalid. 1,073,762 bad conversion. (success 100%)
[match maker] [ chrM ] finished 25,586 lines.
[ patter ] [ chrM ] finished 25,586 lines. (12,793 pairs). 24,734 good, 852 empty, 0 invalid. 5,074 bad conversion. (success 100%)
[match maker] [ chr22 ] finished 6,523,712 lines.
[ patter ] [ chr22 ] finished 6,523,712 lines. (3,261,856 pairs). 4,652,341 good, 1,871,371 empty, 0 invalid. 619,640 bad conversion. (success 100%)
[ patter ] [ chrX ] line 15,000,000 in 2.3 minutes.
[ patter ] [ chr20 ] line 10,000,000 in 2.4 minutes.
[ patter ] [ chrX ] line 20,000,000 in 2.3 minutes.
[ patter ] [ chr20 ] line 15,000,000 in 2.4 minutes.
[match maker] [ chr20 ] finished 16,795,076 lines.
[ patter ] [ chr20 ] finished 16,795,076 lines. (8,397,538 pairs). 10,370,078 good, 6,424,998 empty, 0 invalid. 1,054,457 bad conversion. (success 100%)
[match maker] [ chrX ] finished 22,791,858 lines.
[ patter ] [ chrX ] finished 22,791,858 lines. (11,395,929 pairs). 11,491,467 good, 11,300,391 empty, 0 invalid. 1,078,661 bad conversion. (success 100%)
[match maker] [ chrY ] finished 2,213,784 lines.
[ patter ] [ chrY ] finished 2,213,784 lines. (1,106,892 pairs). 1,074,125 good, 1,139,659 empty, 0 invalid. 86,348 bad conversion. (success 100%)
[wt bam2pat] indexing and generating beta file...
[wt bam2pat] generated ../wgbstools/beta_files/sorted_PM0_ctDNA_WGBS_pe.pat.gz
[wt bam2pat] generated ../wgbstools/beta_files/sorted_PM0_ctDNA_WGBS_pe.beta
```

**Comment by yonniejon** [comment]
When you run `tabix my_pat_file.pat.gz chr22 | head` you seem empty output? the reason I ask is because from the logs it looks like it successfully processed chr22.

**Comment by GMFranceschini** [comment]
You are right, every chromosome has information as expected when checking the head. 
The next step is running the following, if I understood correctly:

```
wgbstools beta_to_table ./path/markers.bed --betas ./path//beta_files/*beta -c 10 | column -t > ./blocks/DMR_markers.tsv
```

The resulting single column for the same file has all NAs for only the even chromosomes.  This pattern of NAs is impossibly dictated by the data itself. 

It is so weird; I am checking back my step, and I hope it's not a mistake from my side, but I can't figure this out.

**Comment by yonniejon** [comment]
what is in your "./path/markers.bed" file? Can you print it here? If it does not have the relevant chromosomes then there won't be any rows in the output of beta_to_table form there.

Who made "./path/markers.bed" ?

**Comment by GMFranceschini** [comment]
The file is a 5-column bed file containing all chromosomes. 
The regions from even chromosomes are not entirely missing in the result; it is just that the average DNA methylation is NA.

markers.bed
```
chr1	909247	909407	11555	11564
chr1	2089534	2089614	54868	54877
chr1	5209128	5209612	120930	120934
chr1	6671108	6671643	149398	149415
chr1	7265351	7266445	159071	159077
chr1	7936604	7937673	169933	169942
chr1	8224708	8224960	174424	174433
...
```

All other chromosomes are included.
If I understand,  the two extra columns are startCpG and endCpG indexes. I have created those blocks myself following your tutorial, and I currently use a subset of them to speed up the testing.

**Comment by yonniejon** [comment]
I mean does markers.bed have any row with chr22?
`cat markers.bed | grep chr22` ?

**Comment by GMFranceschini** [comment]
Yes, it does.

```
chr22	17740724	17740914	26191833	26191839
chr22	18324829	18325161	26202700	26202707
chr22	18474568	18474703	26205275	26205280
...
```

**Comment by yonniejon** [comment]
what happens when you run `tabix one_of_my_pat_files.pat.gz chr22:26191833-26191839` ? any output?

**Comment by GMFranceschini** [comment]
No output, so it looks like those regions are not covered. 
It's odd that this happens for full chromosomes and rarely ever happens on others...

**Comment by yonniejon** [comment]
it makes sense to not find any markers in some chromosomes.
But something is still confusing me - can you post the command you used to create markers.bed?

**Comment by GMFranceschini** [comment]
Sorry for never investigating this further. I suspect that I applied the tool to some corrupted bam files. It was very hard to understand what was wrong with them (in fact, we did not), but in the end, we recently reprocessed everything. Applying `bam2pat` to other similar data works as expected. Closing the issue!
