### ISSUE TITLE
mbias_plot missing / broken by commit 3e5b9bf02f1

### ISSUE THREAD

**Issue by semenko** [nloyfer/wgbs_tools#18]
In the current version, `bam2pat` silently fails with this error:
```
[wt bam2pat] failed in mbias
No module named 'mbias_plot'
```

It looks like that module doesn't exist / isn't committed.

**Comment by nloyfer** [comment]
Thank you, Nick!
You are right, seems like I forgot to commit `mbias_plot.py` in the 0.2.0 release. 
I will fix it a new release.

**Comment by nloyfer** [comment]
See release [0.2.1](https://github.com/nloyfer/wgbs_tools/releases/tag/0.2.1)
