### ISSUE TITLE
Tabix 1.3.1 fix

### ISSUE THREAD

**Issue by MagpiePKU** [nloyfer/wgbs_tools#2]
Hi,

Thank you for the great tools. A quick fix might brought about easier usage by fixing the tabix command parameter in src/index.py with " -p vcf -C ", as lower version tabix does not recognize the "-p bed" command correctly and might bring about trouble. 

Thanks a lot,
Yi

**Comment by nloyfer** [comment]
Hi Yi,
Thank you for letting me know.
I couldn't reproduce the bug, I'm running [tabix 1.3.1](https://github.com/samtools/htslib/releases/tag/1.3.1) and it does recognize the "-p bed" flag...
Anyway, I added an exception for when it fails, replacing the "-p bed" with the equivalent "-s 1 -b 2 -c 3".
