### ISSUE TITLE
split_by_allele and test_bimodal

### ISSUE THREAD

**Issue by rnbatra** [nloyfer/wgbs_tools#20]
Hey. Great package. Not so much of an issue. But rather a question. 
Could you give an example/ tutorial on how to use the `split_by_allele` and `test_bimodal` functions.
Thanks a lot!

**Comment by rnbatra** [comment]
for instance, if i have a methylation BAM and confirmed SNP position, would it be possible to get allele specific methylation (and also split the BAMs)?

**Comment by yonniejon** [comment]
Hi @rnbatra . Sorry for the delay. The tutorial for `split_by_allele` and `test_bimodal` is almost ready.

Regarding your question - yes it is possible.

the main flow of usage is something like this:

	region=chr11:2019196-2019796
	snp=chr11:2019496
	wgbstools bam2pat bams/my_sample.bam -r $region
	wgbstools vis -r $region my_sample.pat.gz
	wgbstools vis -r $region my_sample.pat.gz --uxm 0.65
	wgbstools test_bimodal -r $region my_sample.pat.gz
	wgbstools split_by_allele bams/my_sample.bam $snp C/A --no_beta

**Comment by rnbatra** [comment]
thanks for the quick reply. i also look forward to the tutorial. best!

**Comment by yonniejon** [comment]
The tutorial has been added!
https://github.com/nloyfer/wgbs_tools/blob/master/tutorial/README.md

**Comment by rnbatra** [comment]
Thank you. Would this work suitably for C>T SNPs at CpG sites as well (using reads on the opposite strand for directional libraries)?
