### ISSUE TITLE
split_by_allele C>T SNPs at CpG sites

### ISSUE THREAD

**Issue by rnbatra** [nloyfer/wgbs_tools#25]
Thank you for including the split_by_allele tutorial. Would this work suitably for C>T SNPs at CpG sites as well (using reads on the opposite strand for directional libraries)?

**Comment by yonniejon** [comment]
Hi. Yes. For C->T SNPs both at CpG sites and outside of CpG sites `split_by_allele` considers only reads from the opposite/bottom strand. Similarly it considers only reads from the top strand for G->A SNPs.

This information will be added to the tutorial/documentation.

**Comment by rnbatra** [comment]
thanks for the clarification!
