### ISSUE TITLE
Compiling error for homog...

### ISSUE THREAD

**Issue by hmyh1202** [nloyfer/wgbs_tools#27]
$python3 setup.py
Compiling stdin2beta...
SUCCESS
Compiling stdin2pairs...
SUCCESS
Compiling pat_sampler...
SUCCESS
Compiling patter...
SUCCESS
Compiling bp_patter...
SUCCESS
Compiling snp_patter...
SUCCESS
Compiling match_maker...
SUCCESS
Compiling segmentor...
SUCCESS
Compiling cview...
SUCCESS
Compiling homog...
FAIL
Failed compilation.
Command: g++ -std=c++11 -c -o src/homog/main.o src/homog/main.cpp; g++ -std=c++11 -c -o src/homog/homog.o src/homog/homog.cpp; g++ -std=c++11 -o src/homog/homog src/homog/main.o src/homog/homog.o -lz -lboost_iostreams
return code: 1
stderr:

stdout:
In file included from src/homog/main.cpp:5:0:
src/homog/homog.h:8:48: fatal error: boost/algorithm/string/predicate.hpp: No such file or directory
 #include <boost/algorithm/string/predicate.hpp>
                                                ^
compilation terminated.
In file included from src/homog/homog.cpp:2:0:
src/homog/homog.h:8:48: fatal error: boost/algorithm/string/predicate.hpp: No such file or directory
 #include <boost/algorithm/string/predicate.hpp>
                                                ^
compilation terminated.
g++: error: src/homog/main.o: No such file or directory
g++: error: src/homog/homog.o: No such file or directory

Failed compiling homog
Compiling add_cpg_counts...
SUCCESS
Compiling add_loci...
SUCCESS

**Comment by nloyfer** [comment]
Hi,
`homog` module uses the c++ [`boost` library](https://www.boost.org/), and it seems like you don't have `boost` installed.
I just changed `homog.cpp` such that it doesn't use `boost`, so if you clone the latest version of wgbstools, it should compile for you.

**Comment by mHagiw** [comment]
Hi, I am having trouble with a similar error.
Have you already updated the tool? I cloned the latest version of wgbstools and still get the same error.

**Comment by gat2010** [comment]
Hi, I am also getting the same error.

**Comment by nloyfer** [comment]
You guys are right, my fix didn't work as I expected. I forgot to remove the boost linkage from the `setup.py` file. And I had a couple of other compilation errors. But now I fixed all of that, please try again.

**Comment by gat2010** [comment]
Thanks for the update. It's compiling now.

**Comment by mHagiw** [comment]
Thank you!! I have done.

**Comment by hmyh1202** [comment]
Nice !  Good job
