### ISSUE TITLE
vis heatmap as a file export (pdf, etc.) 

### ISSUE THREAD

**Issue by avilella** [nloyfer/wgbs_tools#29]
Hi,

I've discovered this tool a few days ago and already become a fan of it, as have other scientists in the organization.

Is there a way to produce a file export of the `--heatmap` form of `wgbstools vis`?

Thanks

**Comment by nloyfer** [comment]
Hi Albert.
Thank you, that's very nice to hear.
What kind of file are you talking about?

### text file
You can save the output to a text file in a straightforward way, e.g.
```bash
$ wgbstools vis -r chr17:2916694-2916882 Heart*beta --heatmap > output.txt
# Then view it using a text viewer/editor that can interpret ascii colors, e.g.
$ less -SR output.txt
```

### html file
Sometimes I save the outputs as html files, using [ansi2html](https://pypi.org/project/ansi2html/), then view them in a web browser. You could also use [elinks](http://elinks.or.cz/), if you don't want to leave the terminal.
```bash
$ pip3 install ansi2html
$ wgbstools vis -r chr17:2916694-2916882 Heart*beta --heatmap | ansi2html > output.html
```
I bet there are other unix tool that convert html to pdf or to an image, but haven't tried them myself.

I hope this answers your question.

**Comment by avilella** [comment]
Thanks for your reply. Will try it.

**Comment by avilella** [comment]
ansi2html worked out really well as a solution. Thanks
