### ISSUE TITLE
How to open beta file

### ISSUE THREAD

**Issue by WRui** [nloyfer/wgbs_tools#3]
Hi, could you show me how to read the beta file? In addition, what each column means for pat files?

**Comment by yonniejon** [comment]
It depends what you want to do with the beta file.

If you want to see a visualization then you can try something like:
`wgbstools vis *.beta -r chr3:119528843-119529245 --heatmap`

if you want to open it in python, then something like:
`np.fromfile(beta_file, dtype=np.uint8).reshape((-1, 2))`

**Comment by yonniejon** [comment]
for Pat file columns see [here](https://github.com/nloyfer/wgbs_tools/blob/master/docs/pat_format.md)

**Comment by yonniejon** [comment]
answered the questions in the issue
