### ISSUE TITLE
init_genome error

### ISSUE THREAD

**Issue by lingchuanmeixi** [nloyfer/wgbs_tools#31]
When I enter "wgbtools init_home - f hg38", I get“[wt init] Setting up genome reference files in ./software/wgbs_tools/references/hg38
[wt init] No reference FASTA provided. Attempting to download from
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  938M  100  938M    0     0  6153k      0  0:02:36  0:02:36 --:--:-- 3578k
[wt init] successfully downloaded FASTA. Now gunzip and bgzip it...
bgzip: invalid option -- '@'
[bgzip] No such file or directory: 12
Traceback (most recent call last):File "./software/wgbs_tools/wgbstools", line 96, in <module>
    main()
  File "./software/wgbs_tools/wgbstools", line 63, in main
    importlib.import_module(args.command).main()
  File "./software/wgbs_tools/src/python/init_genome.py", line 297, in main
    InitGenome(args).run()
  File "./software/wgbs_tools/src/python/init_genome.py", line 57, in __init__
    self.get_fasta()
  File "./software/wgbs_tools/src/python/init_genome.py", line 79, in get_fasta
    subprocess.check_call(cmd, shell=True)
  File "./miniconda3/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gunzip ./wgbs_tools/references/hg38/hg38.fa.gz && bgzip -@ 12 ./wgbs_tools/references/hg38/hg38.fa' returned non-zero exit status 1.”

My configuration：
python3 ，pandas version1.5.1，numpy version1.23.4， scipy version1.9.3
htslib version1.13

**Comment by lingchuanmeixi** [comment]
I removed the -@ part of init_genome.py. Although the reason for the error is not clear, the program can run normally.

**Comment by gibberwocky** [comment]
This error is due to using an out-of-date version of htslib. The -@ flag specifies the number of threads to use (http://www.htslib.org/doc/bgzip.html). Updating to htslib 1.18 will solve this.

**Comment by lingchuanmeixi** [comment]
您好，您的邮件已收到，会尽快回复！

**Comment by Guoyixian1989** [comment]
Thank you very much
