### ISSUE TITLE
pat result for short fragments (<150)

### ISSUE THREAD

**Issue by WRui** [nloyfer/wgbs_tools#4]
Hi, I wonder if the fragment is short(<150bp) and R1 and R2 are fully overlapped(2*150 pair-end data), if R1 and R2 (with the same read id )showed different methylation level, what the pat file would output, it will output two different rows or just output one rows that only use methylation levels of R1 or R2?

**Comment by nloyfer** [comment]
Hi,
Read pairs are always concatenated and considered as a single fragment.
If there is overlap, and there are CpGs with different methylation statuses between the two reads, we output `.` for these CpGs (i.e. missing value).
