### ISSUE TITLE
find_markers for RRBS

### ISSUE THREAD

**Issue by AndriesDeKoker** [nloyfer/wgbs_tools#44]
Hi,

I have been trying to U-markers specific for RRBS using
`wgbstools find_markers --betas *hg38.beta -b RRBS_regions_hg38 -g Group_file --only_hypo`

but I was running into this error: https://stackoverflow.com/questions/75798944/how-to-solve-invalid-input-argument-popmean-shapeaxis-must-equal-1-when-r/76235648#76235648
and it seems to be related to the groups where only one beta file is available (because if I'm ignoring these, the code runs)
I made the group file using the 'Group' or 'refined_group' column in suppl table 1
But in the published markerfiles and atlases regions are available for these groups containing one file (Epid-Kerat, Osteo, etc), how should I generate markers for these entities?

Could more info be given about the block-file for the RRBS regions, how these were made? I now performed an in-silico digest with MspI and restricting the fragment lengths from 20-200bp.

Kind regards,
Andries

**Comment by nloyfer** [comment]
About the RRBS atlas.
We selected regions that showed high coverage across multiple samples in some large RRBS cohort ([METABRIC](https://www.nature.com/articles/s41467-021-25661-w)). 
Perhaps this way of choosing "RRBS regions" is not the best way. If you have your own set of regions where you know you are getting high coverage, you can make your own "RRBS atlas".

Once you have a bed file with such regions, you can intersect it with the "whole genome blocks", then find markers with this block file as reference
```bash
bedtools intersect -a blocks.s205.5CpG.bed.gz -b RRBS_regions.bed.gz -wa -u > blocks.5CpG.RRBS.bed
wgbstools find_markers --config_file CONFIG_FILE -b blocks.5CpG.RRBS.bed
```

**Comment by AndriesDeKoker** [comment]
> Hi there,
> 
> Thank you for bringing this bug to my attention. I found that the error message was originating from the `scipy.stats.ttest_ind` function when one of the input arguments was not 2D. This occurs when the target/background has only one sample (n=1).
> 
> I have fixed the issue in `find_markers.py`, and it should now be working as expected. Thank you again.

Hi,

I indeed uninstalled scipy and it ran without ttest.
I pulled this fix and am rerunning with scipy atm

Thanks!

**Comment by nloyfer** [comment]
Right, I accidentally broke something in `beta_to_table.py` in [7df331a](https://github.com/nloyfer/wgbs_tools/commit/7df331a8dee4b58a31a3859c722415d90857c871) (when dealing with the fragmentation warning), and fixed it a few hours later in [f4031b8](https://github.com/nloyfer/wgbs_tools/commit/f4031b8aab620b1c1208308c6ef87057034999ba).
Sorry about that. Please pull again.

**Comment by nloyfer** [comment]
> > About the RRBS atlas. We selected regions that showed high coverage across multiple samples in some large RRBS cohort ([METABRIC](https://www.nature.com/articles/s41467-021-25661-w)). Perhaps this way of choosing "RRBS regions" is not the best way. If you have your own set of regions where you know you are getting high coverage, you can make your own "RRBS atlas".
> > Once you have a bed file with such regions, you can intersect it with the "whole genome blocks", then find markers with this block file as reference
> > ```shell
> > bedtools intersect -a blocks.s205.5CpG.bed.gz -b RRBS_regions.bed.gz -wa -u > blocks.5CpG.RRBS.bed
> > wgbstools find_markers --config_file CONFIG_FILE -b blocks.5CpG.RRBS.bed
> > ```
> 
> aha, well, I guess that getting RRBS regions from a lot of datasets would do the job as well. I did it this way:
> 
> 1. insilico digest with MspI of hg38 (chr - start - stop in bed format)
> 2. wgbstools convert --bed_file RRBS_regions.bed > RRBS_block_file
> 
> This is not the way to do it?

That works too. Intersecting RRBS_regions.bed with the blocks file might be an improvement, because it's possible some of the RRBS regions are not homogeneous (methylation-wise), and it's better to break them into smaller blocks

**Comment by AndriesDeKoker** [comment]
Thank you very much already!

And maybe just a small bug (or I am doing something wrong)
but calling top:25 or top:250 in the config file does not seem to do anything?

**Comment by nloyfer** [comment]
Fixed. Thank you
