### ISSUE TITLE
groups file format

### ISSUE THREAD

**Issue by assafgrw** [nloyfer/wgbs_tools#45]
Hello, I am straggling with the groups file.
I was trying all sorts of formats (full beta file name at the name column, partial, prefix only ect.) and I keep getting the following error:
" Error: 2 prefixes from groups file were not found in input bins:
Adipocytes-Z000000T7
Blood-NK-Z000000UF
Invalid input argument
groups file mismatch binary files"

Any ideas? can you share an example for a group file?

**Comment by AndriesDeKoker** [comment]
I think it is like this:

name,group
GSM5652176_Adipocytes-Z000000T7,Adipocytes
