### ISSUE TITLE
While running bam2pat on ML and MM tag containing  bam file ,reads information is printed on the terminal. 

### ISSUE THREAD

**Issue by vinodsinghjnu** [nloyfer/wgbs_tools#53]
@ Hi, I am getting read information printed on the terminal while running the bam2pat command, is there any way to stop this printing? Or this is due to the presence of  ''Unknown CIGAR character: = '  in the BAM file which is not recognised by WGBStools.
![Screenshot 2023-10-02 at 17 09 26](https://github.com/nloyfer/wgbs_tools/assets/47861162/e47fd625-c165-411f-a6fb-6fef8b2b5185)

**Comment by nloyfer** [comment]
Same problem as in https://github.com/nloyfer/wgbs_tools/issues/52
