### ISSUE TITLE
Tutorials for UXM fragment-level deconvolution 

### ISSUE THREAD

**Issue by willtc10** [nloyfer/wgbs_tools#6]
Hi,
Thank you for all the codes and tutorials. 

I would like to ask if you have any plan updating tutorials about UXM fragment-level deconvolution?

Is the atlas in the unpublished supplementary? Can I use the deconvolution algorithm in Moss et al. (2018) to deconvolve after having the reference atlas from wgbs tools?

**Comment by nloyfer** [comment]
Absolutely!
I will publish the UXM fragment-level deconvolution repository - code and tutorial - as soon as the paper gets accepted for publication. Hopefully soon.

Regarding the atlas - 
Processed files for the 207 samples were deposited to GEO and are available at [GSE186458](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE186458).
Accessing the raw data (fastq files) will be possible once the paper is published.

**Comment by julienlag** [comment]
Hello! Meanwhile, could you please recommend a similar WGBS-based tissue deconvolution software, if it exists?

**Comment by nloyfer** [comment]
Hi,
Our paper finally got accepted.

#### raw data
The fastq files are now being deposited to EGA. The accession will be published with the paper, any day now.

#### `pat` files
I uploaded all the `pat` files to [GSE186458](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE186458).

#### Deconvolution
The UXM deconvolution repository is now available here:
[https://github.com/nloyfer/UXM_deconv](https://github.com/nloyfer/UXM_deconv)
It includes a reference atlas and the code. Should be pretty straightforward to download and run it on your own data.

#### Other fragment-level deconvolution methods
I don't know any other published methods (at the moment), other than [Celfie](https://www.biorxiv.org/content/10.1101/2022.09.30.510300v1.full).
I haven't tried it yet, but based on their previous work I bet it's good.
