### ISSUE TITLE
wgbstools for single base DNA methylation

### ISSUE THREAD

**Issue by hengbingao** [nloyfer/wgbs_tools#70]
Hi,
wgbstools is a good tool for DNA methylation data analysis, but I wonder if it could generate single base CG and CH methylation allc files which are compatiable to bismark and methylpy?  Or if it is just suitable for some big genomic region DNA methylation analysis?

thanks!

**Comment by nloyfer** [comment]
Hi @hengbingao ,
Unfortunately, wgbstools only supports CpG methylation at the moment.
