### ISSUE TITLE
bam2pat-combine OT and OB?

### ISSUE THREAD

**Issue by chang-bwl** [nloyfer/wgbs_tools#76]
Hi,
wgbstools is very convenient for processing DNA methylation data. I would like to confirm: When using bam2pat, does it merge the methylation status of CpG sites for both the OT and OB strands in the BAM file? For example, **chr3 5394764 CCCC 26** represents reads starting from cpg_index 5394764, which may include the OT strand at chr3:x or the OB strand at chr3:x+1. However, it is not possible to differentiate them from the pat file, is that correct?
Thanks!

**Comment by yonniejon** [comment]
Hi. Yes, you are correct. The pat file includes both but these cannot be differentiated from the pat file.
