### ISSUE TITLE
bed2beta error？

### ISSUE THREAD

**Issue by bresf** [nloyfer/wgbs_tools#81]
Hi:
    wgbstools is a great tool! 
    I noticed that this line of code might have some issues，
[https://github.com/nloyfer/wgbs_tools/blob/master/src/python/bed2beta.py](url)
code:
`df = pd.read_csv(bed_path, sep='\t', header=header,
                     names=['chr', 'start', 'meth', 'total'],
                     usecols=[0, 1, 3, 4], nrows=nrows)`
 should be:
"names=['chr', 'start', 'end', 'meth', 'total']"

thank you

**Comment by yonniejon** [comment]
Hi, this is not an issue as usecols is set to skip the column at index 2. Thanks!
