### ISSUE TITLE
how to solve /wgbs_tools/references/hg19/CpG.bed.gz

### ISSUE THREAD

**Issue by Taaannnuuujjjjaa** [nloyfer/wgbs_tools#82]
$ wgbstools vis -r chr4:83821889-83841122 GSE186458_RAW/GSM5652221_Oligodendrocytes-Z0000042L.pat.gz
Invalid input argument
Invalid reference path: /hdfs3/data/biodata/wgbs_tools/references/hg19/CpG.bed.gz

**Comment by yonniejon** [comment]
Hi. did you run the command `wgbstools init_genome hg19`? In general wgbstools requires there to be a reference genome directory with several files created by the init_genome command. Your error is saying that one of the required files does not exist.
