### ISSUE TITLE
(+) meaning?

### ISSUE THREAD

**Issue by sehee59** [nloyfer/wgbs_tools#84]
What does the (+) mean for each CpG site in that output, and if it's +one or 1 CpG, wouldn't the dots underneath correspond to the base level, but not the +2base level? 
How should I interpret this?
<img width="605" alt="스크린샷 2024-08-20 오전 11 21 22" src="https://github.com/user-attachments/assets/f3108385-8b66-401b-bdb2-dd34f401ffe2">

**Comment by yonniejon** [comment]
The plus marks at the top of the visualization refer to the CpG sites within the specified region. What is visualized is all reads from the pat file intersecting the specified region (but possibly containing reads with CpGs outside of the specified region). So in your first example, there are 3 CpGs in the specified region, while the top most and bottom most read contains CpGs outside of the region.

**Comment by sehee59** [comment]
So you mean a dinucleotide with one CpG site per circle point representing that read?

**Comment by yonniejon** [comment]
I think what you wrote is correct - but I am not sure I understood so I will rephrase. Each circle represents the methylation status of the cytosine at a known CpG site (according to the reference list of CpGs). So if a circle is green, the cytosine was called as unmethylated, if the circle is red the cytosine was called methylated. Each read/read-pair consists of closely spaced circles (reads are separated by lines or sometimes spaces also). So in your image each line contains one read/read-pair. The first read contains 5 CpG sites. The first two were called as methylated, one was not called, and the last two were called as unmethylated. The first two are within the input region chr2:2638534-2638792. The others are outside of the region. The next line shows a read covering two CpG sites (each within the input region) where the first is methylated and the second is unmethylated.

**Comment by sehee59** [comment]
Yes. I understand. 
Thank you for your kind reply.
