### ISSUE TITLE
visualisation output 

### ISSUE THREAD

**Issue by magdaliput** [nloyfer/wgbs_tools#85]
Hi,
I have two problems concerning saving the plots. 
The first one is outcome of pat_fig. It is great that I can get all the samples on 1 plot, however, I would like to change the number of samples per row. I analyze 18 samples (3 replicates for each cell type) and would like to have 3 in row. The scripts generates plot with 5 samples per row. Is it possible to change this?
![cg00256374-cg02480840](https://github.com/user-attachments/assets/a7ee4dcf-2dc5-4307-9067-d9fc7a68ca59)

The other issue I have is the vis command with *.beta files (numbers representing % of methylation). The visualisation is great however I cant save the results to the file. The -o option is red, there are no warnings but no file is saved. Do you know what could be posibbly the problem?
example code:
wgbstools vis *.beta -r chr19:1226523-1226535 -o test.png

Thanks in advance for answear and for awsome tools for analysis :)
Cheers
Magda

**Comment by yonniejon** [comment]
For the pat_fig you have col_wrap argument which defaults to 5. You can change it to 3.

**Comment by yonniejon** [comment]
about the beta vis - i am not sure if there is an alternative but vis command does not provide this option for saving output as an image.

**Comment by magdaliput** [comment]
> For the pat_fig you have col_wrap argument which defaults to 5. You can change it to 3.

thank you for reply
