### ISSUE TITLE
BAM2PAT nanopore

### ISSUE THREAD

**Issue by Sepideh89** [nloyfer/wgbs_tools#88]
Dear WGBS Team,

I ran this command:
wgbstools bam2pat -np test.bam
this is a nanopore **unaligned** bamfile. seems to me wgbstools still trying to catch the chr name (while its an unaligned bam file, doesn't have chr name,etc.), however -np flag is active.
this is the output of that command, could you please let me know if there is anything wrong running that command? 

######################################################
Failed retrieving valid chromosome names. Perhaps you are using a wrong genome reference. Try running:
		wgbstools set_default_ref -ls
Invalid input argument
Failed

##########################################################
Appreciate it in advance 
Sep.

**Comment by yonniejon** [comment]
Hi Sep,
the input to wgbstools is required to be aligned. The pat format is only defined on aligned data as it requires reference CpG site genomic positions.

**Comment by Sepideh89** [comment]
Thank you for your guidance.

**Comment by Sepideh89** [comment]
This is Whole Genome Sequencing data. What's your advice regarding that?

**Comment by yonniejon** [comment]
For whole genome sequencing I recommend aligning the data to a reference genome  😅 . Why not align it?
